import Head from 'next/head'
import questions from '../questions.json'
import { useState } from 'react'
import Question from '../components/question'
import Answer from '../components/answer'

export default function Home() {
	const [id, setId] = useState( 0 )

	const handleNext = () => {
		if ( id == questions.length - 1 ) {
			setId( 0 )
			return
		}

		setId( id + 1 )
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-slate-800 v-screen h-screen text-white flex overflow-hidden">
				<div className="flex-auto w-1/2 bg-slate-900 h-full overflow-y-auto p-3">
					{
						questions[id] && <Question key={'question' + id} item={questions[id]} />
					}
				</div>
				
				<div className="flex-auto w-1/2 h-screen flex flex-col overflow-y-auto p-3">
				{questions[id].answerOptions.map((choice, index) => (
					<Answer 
						key={'answer' + index} 
						choice={choice} 
						choiceName={'answer' + id} 
						choiceId={'answer-' + index + '/asd'}
						isCorrect={choice.isCorrect ?? false} />
				))}

					<nav>
						<button className="bg-green-400 px-5 py-2.5 rounded-lg" onClick={handleNext}>Next</button>
					</nav>
				</div>

			</main>
		</>
	)
}
